apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: bnjmn034/user-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: DB_URL
              value: jdbc:postgresql://user-db:5432/userdb
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef: { name: app-secrets, key: DB_USERNAME }
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef: { name: app-secrets, key: DB_PASSWORD }
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef: { name: app-secrets, key: JWT_SECRET }
            - name: OTEL_SERVICE_NAME
              value: user-service
            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: http://jaeger:4318/v1/traces
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: http/protobuf
            - name: OTEL_TRACES_EXPORTER
              value: otlp
            - name: OTEL_METRICS_EXPORTER
              value: none
            - name: OTEL_LOGS_EXPORTER
              value: none
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - port: 8081
      targetPort: 8081
