server.port=8082
spring.application.name=task-service

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/taskdb}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# User Service ile AYNI secret olmali
jwt.secret=${JWT_SECRET:cok-gizli-bir-anahtar-en-az-32-karakter-olmali-12345}

management.endpoints.web.exposure.include=health,prometheus
management.endpoint.prometheus.access=unrestricted
management.metrics.tags.application=${spring.application.name}
